# -*- coding: utf-8 -*-
"""Modern Data Group Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MdJl8T2RC55nhZfTrgdSKs8A9H1gQUNZ

Question 3"
"""