# -*- coding: utf-8 -*-
"""Modern Data Question Three

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1f38s4QOOdmSTxg-0ohbuT0BMyJwhlqkW
"""

"""Question 3: Tortoise and Hare Race Simulation"""

import random
import time

tortoise_pos = 1
hare_pos = 1
finish_line = 70

print("BANG !!!!")
print("AND THEY'RE OFF !!!!\n")

def move_tortoise():
"""This determines the tortoise's move based on random chance."""
    i = random.randint(1, 10)
    if 1 <= i <= 5:
        return 3
    elif 6 <= i <= 7:
        return -6
    else:
        return 1

def move_hare():
"""This determines the hare's move based on random chance."""
    i = random.randint(1, 10)
    if 1 <= i <= 2:
        return 0
    elif 3 <= i <= 4:
        return 9
    elif i == 5:
        return -12
    elif 6 <= i <= 8:
        return 1
    else:
        return -2

def print_track(tortoise_pos, hare_pos):
"""This prints the race track -- showing the toirtoise and hare positions."""
    track = ['_'] * finish_line
    t_pos = max(0, tortoise_pos - 1)
    h_pos = max(0, hare_pos - 1)


    t_pos = min(t_pos, finish_line - 1)
    h_pos = min(h_pos, finish_line - 1)

    if tortoise_pos == hare_pos:
        track[t_pos] = "OUCH!" #this is the collision 
    else:
        track[t_pos] = "T"
        track[h_pos] = "H"


    print(''.join(str(x).ljust(1) for x in track))

#this actually runs the entire race 
while tortoise_pos < finish_line and hare_pos < finish_line:
    tortoise_pos += move_tortoise()
    hare_pos += move_hare()


    if tortoise_pos < 1:
        tortoise_pos = 1
    if hare_pos < 1:
        hare_pos = 1

    print_track(tortoise_pos, hare_pos)
    time.sleep(0.2) #did this so there is a slight pause (looks better)

#determines the overall winner each time
if tortoise_pos >= finish_line and hare_pos >= finish_line:
    print("\nIt's a tie!")
elif tortoise_pos >= finish_line:
    print("\nTORTOISE WINS!!! YAY!!!")
else:
    print("\nHare wins. Yuch.")
