# -*- coding: utf-8 -*-
"""Modern Data Group Project

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MdJl8T2RC55nhZfTrgdSKs8A9H1gQUNZ
"""

"""Question 3: Tortoise and Hare Race Simulation"""

import random
import time

# Initialize starting positions
tortoise_pos = 1
hare_pos = 1
finish_line = 70

# Print starting message
print("BANG !!!!")
print("AND THEY'RE OFF !!!!\n")

def move_tortoise():
    """Determine tortoise's move based on random chance."""
    i = random.randint(1, 10)
    if 1 <= i <= 5:       # Fast plod: 50%
        return 3
    elif 6 <= i <= 7:     # Slip: 20%
        return -6
    else:                 # Slow plod: 30%
        return 1

def move_hare():
    """Determine hare's move based on random chance."""
    i = random.randint(1, 10)
    if 1 <= i <= 2:       # Sleep: 20%
        return 0
    elif 3 <= i <= 4:     # Big hop: 20%
        return 9
    elif i == 5:          # Big slip: 10%
        return -12
    elif 6 <= i <= 8:     # Small hop: 30%
        return 1
    else:                 # Small slip: 20%
        return -2

def print_track(tortoise_pos, hare_pos):
    """Prints the race track showing tortoise and hare positions."""
    track = ['_'] * finish_line  # Create empty track
    t_pos = max(0, tortoise_pos - 1)
    h_pos = max(0, hare_pos - 1)

    # Ensure t_pos and h_pos are within the track bounds
    t_pos = min(t_pos, finish_line - 1)
    h_pos = min(h_pos, finish_line - 1)

    if tortoise_pos == hare_pos:
        track[t_pos] = "OUCH!"  # Collision!
    else:
        track[t_pos] = "T"
        track[h_pos] = "H"

    # Join the track into a string and print it
    print(''.join(str(x).ljust(1) for x in track))

# Run the race
while tortoise_pos < finish_line and hare_pos < finish_line:
    tortoise_pos += move_tortoise()
    hare_pos += move_hare()

    # Ensure positions are not less than 1
    if tortoise_pos < 1:
        tortoise_pos = 1
    if hare_pos < 1:
        hare_pos = 1

    print_track(tortoise_pos, hare_pos)
    time.sleep(0.2)  # Slight pause for better viewing

# Determine winner
if tortoise_pos >= finish_line and hare_pos >= finish_line:
    print("\nIt's a tie!")
elif tortoise_pos >= finish_line:
    print("\nTORTOISE WINS!!! YAY!!!")
else:
    print("\nHare wins. Yuch.")